rdkcentral/Lightning-CLI

- .eslintrc.js
- CONTRIBUTING.md
- COPYING
- NOTICE
- bin/index.js
- fixtures/eslint/.eslintrc.js
- fixtures/lightning-app/src/App.js
- fixtures/lightning-app/src/index.js
- src/actions/build.js
- src/actions/create.js
- src/actions/dev.js
- src/actions/docs.js
- src/actions/release.js
- src/actions/serve.js
- src/actions/upload.js
- src/actions/watch.js
- src/alias/wpe-lightning.js
- src/configs/rollup.es5.config.js
- src/configs/rollup.es6.config.js
- src/helpers/ask.js
- src/helpers/build.js
- src/helpers/exit.js
- src/helpers/sequence.js
- src/helpers/spinner.js
- src/helpers/uptodate.js
BLDKCMF-9 Compliance Issues in Lightning-CLI
> BLDKCMF-9 Compliance Issues in Lightning-CLI

- docs/environmentvariables.md
- src/actions/serve.js
Proxies all requests which can't be resolved locally to the given url
> Add support for LNG_SERVE_PROXY

- src/actions/serve.js
Updated code as per the comments from Michiel.
> Fix windows port issue

- package.json
- src/actions/docs.js
- src/actions/serve.js
- src/helpers/build.js
- src/helpers/localinstallationcheck.js
Added support for using the CLI locally and globally.
> Added support for local cli execution

- src/configs/esbuild.es5.config.js
- src/configs/esbuild.es6.config.js
- src/plugins/esbuild-alias.js
Fixed the following issues in this PR :
1. File path issue when there is no extension for the file.
2. Updated esbuild.es5.config file with proper aliases
3. Updated esbuild.es6.config file with proper regex for wpe-lightning comparison
> Addressed file path issue, esbuild-config issues

- docs/README.md
> Spelling fix

- package.json
- src/configs/esbuild.es5.config.js
- src/configs/esbuild.es6.config.js
Esbuild is still not ready for production. Ver 0.8.x has many issues but version 0.12.20 is very promising.
> Bump esbuild 0.12.20

- package.json
Updated Rollup Common JS plugin to make sure the application loading in browser does not throw any error and resolves the below issue 
https://github.com/rdkcentral/Lightning-CLI/issues/156
> Updated rollup common js plugin to resolve axios issue

- src/actions/create.js
Added support for the below feature : 
https://github.com/rdkcentral/Lightning-CLI/issues/160
> Make default value for App identifier match App name #160

- fixtures/typescript/package.json
- fixtures/typescript/src/App.ts
- fixtures/typescript/src/index.ts
- package-lock.json
- package.json
- src/actions/create.js
- src/configs/rollup.es5.config.js
- src/configs/rollup.es6.config.js
- src/helpers/build.js
Added support for typescript project(from the PR140)
> Added support for typescript and make sure it works with both rollup and esbuild

- package-lock.json
Updated package-lock.json file
> Updated package-lock.json file

- src/actions/create.js
Added support for both ignoring space and specialcharacters in the app identifier
> Added support for both ignoring space and specialcharacters in the app identifier

- docs/commands/dist.md
Updated watch functionality in the dist docs
> Updated dist docs with watch command

- src/actions/serve.js
- src/configs/esbuild.es5.config.js
- src/configs/esbuild.es6.config.js
- src/configs/rollup.es5.config.js
Fixed issue related to the serve when the custom build folder is specified in env variable
> Buildfolderservefix

- src/actions/serve.js
> Fix orphan process on Windows

- src/configs/esbuild.es5.config.js
- src/configs/esbuild.es6.config.js
Added support for typescript with esbuild
> Added esbuild typescript support

- docs/environmentvariables.md
- src/configs/esbuild.es5.config.js
- src/configs/esbuild.es6.config.js
- src/configs/rollup.es5.config.js
- src/configs/rollup.es6.config.js
- src/helpers/build.js
Added support for browser build support and used PR130 for these changes
> Added support for browser build support and used PR130 for these changes

- src/helpers/dist.js
Another leftover from #154 support for monorepos
> Fix dist with monorepo setup

- CHANGELOG.md
- package-lock.json
- package.json
Updated version to 2.8.1 and added changelog
> 2.8.1 Cli release

- src/helpers/build.js
Fixed issue related to gitignore
> Fix for gitignore getting written every time we run a build

- src/configs/esbuild.es5.config.js
- src/configs/esbuild.es6.config.js
- src/configs/rollup.es5.config.js
- src/configs/rollup.es6.config.js
In the app you alse have the APP_ variables from process.env now https://github.com/rdkcentral/Lightning-CLI/issues/214
> App variables from process.env are now available

- CHANGELOG.md
- docs/environmentvariables.md
- fixtures/js/lightning-app/src/App.js
- fixtures/ts/lightning-app/src/App.ts
- package-lock.json
- package.json
- src/actions/serve.js
- src/configs/esbuild.es5.config.js
- src/configs/esbuild.es6.config.js
- src/configs/rollup.es5.config.js
- src/helpers/build.js
- Resolved issue with unnecessary license text being added to apps created with CLI (#226)
- Fixed build issue related to rollup path (#222)
- Fixed issue where sourcemap files were not generated when using `esbuild` (#228)
- Added support for CORS  (#225)
> Release - v2.11.0

- src/actions/dist.js
- src/configs/esbuild.es5.config.js
- src/configs/esbuild.es6.config.js
- src/helpers/build.js
This PR fixes the CLI issue #242
> Updated code to address the cli issue 242

- CHANGELOG.md
- package-lock.json
- package.json
- src/configs/esbuild.es5.config.js
- src/configs/esbuild.es6.config.js
- src/configs/rollup.es5.config.js
- src/configs/rollup.es6.config.js
- Fixed customConfig error while using esbuild (missing a check if it is undefined)
- Added a check if the custom config file exists and add a warning if it does not (for both esbuild & rollup)
- Bumped the version to 2.14.1
> Fixed customConfig errors

- CHANGELOG.md
- package-lock.json
- package.json
- src/configs/esbuild.es5.config.js
- src/configs/esbuild.es6.config.js
- src/configs/rollup.es5.config.js
- src/configs/rollup.es6.config.js
Added file extension to validate the custom config file existence
> Added file extension to the custom config files
